version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:13.3.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: install-jest-express
          command: npm install
      - run:
          name: test
          command: npm test
  deploy:
    docker: 
      - image: circleci/node:13.3.0 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run:
          name: heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master 
